
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MIS
{

using System;
    using System.Collections.Generic;
    
public partial class DailyFollowUpInfo
{

    public int Id { get; set; }

    public Nullable<int> F_Id { get; set; }

    public string F_Check { get; set; }

    public string Remark { get; set; }

    public Nullable<System.DateTime> F_Date { get; set; }



    public virtual FollowUpTable FollowUpTable { get; set; }

}

}
