
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MIS
{

using System;
    using System.Collections.Generic;
    
public partial class GiveAndReciveDeailTable
{

    public int Id { get; set; }

    public Nullable<System.DateTime> Date { get; set; }

    public string GiverName { get; set; }

    public string ReciverName { get; set; }

    public string Time { get; set; }

    public string Reson { get; set; }

    public Nullable<int> MoneyType { get; set; }

    public Nullable<int> Money { get; set; }

}

}
