
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MIS
{

using System;
    using System.Collections.Generic;
    
public partial class PersonInfoTable
{

    public int Id { get; set; }

    public string P_Name { get; set; }

    public Nullable<int> P_PostId { get; set; }

    public Nullable<int> P_Phone { get; set; }

    public string P_Brand { get; set; }

    public string P_DeviceSerial { get; set; }

    public string P_DeviceLocation { get; set; }

    public string P_Remark { get; set; }



    public virtual PostInfoTable PostInfoTable { get; set; }

}

}
