
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MIS
{

using System;
    using System.Collections.Generic;
    
public partial class FollowUpTable
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public FollowUpTable()
    {

        this.DailyFollowUpInfoes = new HashSet<DailyFollowUpInfo>();

    }


    public int Id { get; set; }

    public string FollowUp { get; set; }

    public string Remark { get; set; }

    public Nullable<int> PId { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DailyFollowUpInfo> DailyFollowUpInfoes { get; set; }

    public virtual PurposeInfo PurposeInfo { get; set; }

}

}
