
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MIS
{

    using System;
    using System.Collections.Generic;
    using System.Data;

    public partial class FollowUpTable
{

    public int Id { get; set; }

    public string FollowUp { get; set; }

    public string Remark { get; set; }

    public Nullable<int> PId { get; set; }



    public virtual PurposeInfo PurposeInfo { get; set; }

        internal DataRow NewRow()
        {
            throw new NotImplementedException();
        }
    }

}
