
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MIS
{

using System;
    using System.Collections.Generic;
    
public partial class ProductDetail
{

    public int Id { get; set; }

    public string P_Name { get; set; }

    public Nullable<int> P_DepartmentId { get; set; }

    public Nullable<int> P_PurchasePrice { get; set; }

    public string P_Description { get; set; }



    public virtual DepartmentInfo DepartmentInfo { get; set; }

}

}
