
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MIS
{

using System;
    using System.Collections.Generic;
    
public partial class ProductDetail
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ProductDetail()
    {

        this.StockDetails = new HashSet<StockDetail>();

        this.StockOutDetails = new HashSet<StockOutDetail>();

    }


    public int Id { get; set; }

    public string P_Name { get; set; }

    public Nullable<int> P_DepartmentId { get; set; }

    public Nullable<int> P_PurchasePrice { get; set; }

    public string P_Description { get; set; }



    public virtual DepartmentInfo DepartmentInfo { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<StockDetail> StockDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<StockOutDetail> StockOutDetails { get; set; }

}

}
