
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MIS
{

using System;
    using System.Collections.Generic;
    
public partial class StockOutDetail
{

    public int Id { get; set; }

    public Nullable<int> Reg { get; set; }

    public string ReceiverName { get; set; }

    public Nullable<int> P_Id { get; set; }

    public Nullable<int> Qty { get; set; }

    public Nullable<System.DateTime> Date { get; set; }

    public string Remark { get; set; }



    public virtual ProductDetail ProductDetail { get; set; }

}

}
